#!/bin/sh
 
if [ $# -ne 3 ]; then
  echo "Usage: ghe-pr <remote_name> <base_branch> <head_branch>";
  exit;
fi
 
 
REMOTE=$1
BASE=$2
HEAD=$3
ROOT_URL="https://github.com" # for GHE ROOTURL
REMOTE_URL=`git config --get remote.${REMOTE}.url`

if [ `echo $REMOTE_URL | grep 'github.com'` ]; then
 ROOT_URL="https://github.com";
fi

DIR=`echo "$REMOTE_URL" | cut -f2 -d: | cut -f1 -d.`
echo ""
echo " URL: $ROOT_URL/$DIR/compare/$BASE...$HEAD?expand=1"
echo ""
